#!/usr/bin/expect -f

if { [llength $argv] != 3 } {
	puts "example:autologinssh <user> <host> <pw>"
	exit 1
}
set user [lindex $argv 0]
set host [lindex $argv 1]
set password [lindex $argv 2]

set timeout 60
spawn ssh $user@$host
expect "Password:"
send "$password\r"
interact
#expect eof
#exit
