#!/bin/bash

if [ -z $1 ];then
    echo "prework [IP]"
    echo "example:prework 213"
    exit
fi

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`
. "$bin"/conf.sh

IP=10.4.35.$1


#echo "$IP"
ssh $LOGIN_USER@$IP


